#- name: Delete unwanted Instances for this vpc 
#  ec2:
#     state: absent
#     region: "{{ region }}"
#     aws_secret_key: "{{ aws_secret_key }}"
#     aws_access_key: "{{ aws_access_key }}"
#     instance_ids: "{{ to_remove.instance_id }}"

- name: Create bastion instance
  ec2:
    region: "{{ region }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    keypair: "{{ keypair }}"
    instance_profile_name: "deployer"
    assign_public_ip: "{{ assign_public_ip }}"
    image: "{{ image }}"
    group_id: "{{ builder_sg.group_id }}"
    vpc_subnet_id: "{{ builder_vpc.subnets[0].id }}"
    wait: true
    instance_tags: "{{ instance_tags }}"
    exact_count: "{{ exact_count }}"
    count_tag: "{{ count_tag }}"
  register: ec2_bastion

- debug: var=ec2_bastion
- debug: var=item
  with_dict: ec2_bastion

- route53:
    command: create
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    zone: cloud.ownenergy.com.au
    record: bastion.cloud.ownenergy.com.au
    type: A
    ttl: 1200
    value: "{{ ec2_bastion.tagged_instances[0].public_ip }}"
#      with_items: ec2_bastion.tagged_instances

- route53:
    command: create
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    zone: own.internal
    record: bastion.own.internal
    type: A
    ttl: 1200
#      value: "{{ item.private_ip }}"
    value: "{{ ec2_bastion.tagged_instances[0].private_ip }}"
#      with_items: ec2_bastion.tagged_instances
